version: '3'

services:
  db:
    image: postgres
    container_name: "element29Postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: gunicorn element29.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db